
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140801 (SVN rev 36)
// Tue Mar 07 14:52:10 ART 2017
//----------------------------------------------------

package tp.compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTOYCOMA = 10;
  public static final int INTEGER = 25;
  public static final int CONTINUE = 19;
  public static final int FLT = 21;
  public static final int DIVENTERA = 30;
  public static final int INT = 20;
  public static final int LCORCHETE = 6;
  public static final int FOR = 16;
  public static final int IGUAL = 34;
  public static final int LLLAVE = 4;
  public static final int LPARENTESIS = 8;
  public static final int CLASS = 2;
  public static final int RLLAVE = 5;
  public static final int SUMA = 27;
  public static final int IF = 13;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 24;
  public static final int RETURN = 15;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int MENOS = 28;
  public static final int MENOR = 33;
  public static final int BREAK = 18;
  public static final int VOID = 22;
  public static final int EXTERNINVK = 12;
  public static final int ADMIRACION = 37;
  public static final int MAYOR = 32;
  public static final int ELSE = 14;
  public static final int WHILE = 17;
  public static final int RCORCHETE = 7;
  public static final int FLOAT = 26;
  public static final int CONJUNCION = 35;
  public static final int STRING = 23;
  public static final int DISYUNCION = 36;
  public static final int FALSE = 39;
  public static final int DIVISION = 29;
  public static final int RPARENTESIS = 9;
  public static final int MULTIPLICACION = 31;
}

